from src.schedulers.multi_scheduling import MultilevelQueueScheduling
from src.schedulers.non_preemprive_priority_scheduling import NonPreemptivePriorityScheduling
from src.schedulers.non_preemptive_sjf import NonPreemptiveSJFScheduler
from src.schedulers.preemprive_priority_scheduling import PreemptivePriorityScheduling
from src.schedulers.preemptive_sjf import PreemptiveSJFScheduler
from src.schedulers.round_robin import RoundRobin
from src.schedulers.fcfs import FcFsScheduler